services:
  postgres:
    image: postgres
    container_name: home_library_db
    env_file: .env
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${PORT_DB}:${PORT_DB}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql 
    networks:
      - app_network

  app:
    image: juliabel5/nodejs2024q3-service-app:latest
    #build:
      #context: .
      #dockerfile: Dockerfile
    container_name: home_library_app
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${PORT_DB}/home_library_db
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    develop:
      watch:
      - action: sync+restart
        path: ./src
        target: /app/src
        ignore:
          - node_modules
    restart: always
    volumes:
      - logs_data:/app/logs 
        
    networks:
      - app_network

volumes:
  postgres_data:
  postgres_logs: 
  logs_data:    

networks:
  app_network:
    driver: bridge
